name: "Conventional Commits linter"
description: "Installs and use commitizen to check if the commit message conforms to `Conventional Commits`(https://www.conventionalcommits.org/). Must setup-python before."
author: "Yibu Ma"
branding:
  icon: "file-text"
  color: "wheat"
inputs:
  message:
    description: "commit message that needs to be checked"
    required: false
    default: ""
  rev-range:
    description: "a range of git rev to check. e.g, main..HEAD"
    required: false
  allow-abort:
    description: "allow empty commit messages, which typically abort a commit"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install commitizen
      run: pip install -U commitizen
      shell: bash

    - name: test
      run: git log -10 --decorate
      shell: bash

    - name: Run commitizen with message
      if: ${{ inputs.message }}
      run: cz check -m ${{ inputs.message }}
      shell: bash

    - name: Show be check commit message
      if: ${{ !inputs.message }}
      run: git log ${{ inputs.rev-range}} --decorate
      shell: bash

    - name: Run commitizen
      if: ${{ !inputs.message && inputs.allow-abort == 'false' }}
      run: cz check --rev-range ${{ inputs.rev-range }}
      shell: bash

    - name: Run commitizen allow empty commit
      if: ${{ !inputs.message && inputs.allow-abort != 'false' }}
      run: cz check --rev-range ${{ inputs.rev-range }} --allow-abort
      shell: bash
