name: Push conventional commits linter

on: workflow_call

jobs:
  push-conventional-commits-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test
        run: |
          git log -10
          echo ${{toJSON(github)}}
      - name: Check push commits
        if: ${{ github.event.before != '0000000000000000000000000000000000000000' }}
        uses: yibuma/devops/.github/actions/conventional-commits-linter@main
        with:
          rev-range: '${{github.event.before}}...HEAD'

      - name: Check push commits without before
        if: ${{ github.event.before == '0000000000000000000000000000000000000000' }}
        uses: yibuma/devops/.github/actions/conventional-commits-linter@main
        with:
          rev-range: '${{github.event.repository.default_branch}}...HEAD'
