name: Push conventional commits linter

on: workflow_call

jobs:
  push-conventional-commits-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check push commits
        uses: yibuma/devops/.github/actions/conventional-commits-linter
        with:
          rev-range: '${{github.event.before}}...HEAD'
