name: Auto release tag caller

on:
  pull_request_target:
    paths:
      - 'CHANGELOG.md'
    types:
      - closed
    branches:
      - main

jobs:
  release-pull-request:
    uses: yibuma/devops/.github/workflows/release-tag.yml@main
    with:
      release-type: 'simple'
      token: ${{ secrets.GITHUB_TOKEN }}
