name: Release pull request

on:
  workflow_call:
    inputs:
      release-type:
        required: true
        type: string
      token:
        required: true
        type: string

jobs:
  release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: ${{ inputs.release-type }}
          token: ${{ inputs.token }}
          command: release-pr
