name: Tag and github release caller

on:
  pull_request_target:
    paths:
      - 'CHANGELOG.md'
    types:
      - closed
    branches:
      - main

jobs:
  tag-github-release:
    uses: yibuma/devops/.github/workflows/tag-github-release.yml@main
    with:
      release-type: 'simple'
